name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1' 

      - name: Use Julia cache
        uses: julia-actions/cache@v2

      - name: Add Cosmonstants to environment
        run: |
          git clone https://github.com/rafaelab/Cosmonstants.jl.git
          julia --project -e '
            using Pkg; Pkg.develop(path = "Cosmonstants.jl")
            Pkg.instantiate()'

      - name: Install dependencies
        run: julia --project -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: julia --project -e 'using Pkg; Pkg.test()'
