name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        
        - uses: julia-actions/setup-julia@v2
          with:
            version: "1"

        - name: Use Julia cache
          uses: julia-actions/cache@v2

        - name: Install dependencies
          run: |
            git clone https://github.com/rafaelab/Cosmonstants.jl.git
            julia --project=docs -e '
              using Pkg
              Pkg.develop(path = ".")
              Pkg.develop(url = "https://github.com/rafaelab/Cosmonstants.jl")
              Pkg.instantiate()'

        - run: julia --project=docs docs/make.jl
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
